### ISSUE TITLE
Libcxx is not compiling.

### ISSUE THREAD

**Issue by Manish-Kala-Jaat** [Meulengracht/MollenOS#211]
When compiling the millennium os with the command :- make VALI_ARCH=amd64 CROSS=pointing toolchain.
It runs good till the Libyan.lib but after that the turn of getting compiling of libcxx comes but
It is giving the error saying that the := LIBCXX_ENABLE_STATIC_ABI_LIBRARY  requires Python  but it is not found.
Let me clear you this issue looks related to cmake but I have installed all the pre-requisites given in the makefile of mollen os and vali toolchain aiso.

 Here are the screenshots...

**SCREENSHOTS**

![Screenshot (5324)](https://user-images.githubusercontent.com/49841018/56853158-83690780-6941-11e9-9df3-fb3eb0ff3622.png)
![Screenshot (5325)](https://user-images.githubusercontent.com/49841018/56853157-83690780-6941-11e9-8cfe-f149582471ff.png)

![Screenshot (5329)](https://user-images.githubusercontent.com/49841018/56853159-84019e00-6941-11e9-984a-c165baa4960d.png)

**Comment by Meulengracht** [comment]
You must run the tools/depends.sh, it will install the Vali.cmake platform file required for using cmake build with vali

**Comment by Meulengracht** [comment]
See link https://github.com/Meulengracht/MollenOS#setting-up-for-os-development

**Comment by Meulengracht** [comment]
Also if you are building the 64 bit build please pull latest changes as they fixed an issue with VirtualBox startup

**Comment by Meulengracht** [comment]
Please close this issue if you are able to compile after these instructions

**Comment by Manish-Kala-Jaat** [comment]
Thanks man it worked .
