### ISSUE TITLE
how to launch console or other application

### ISSUE THREAD

**Issue by Manish-Kala-Jaat** [Meulengracht/MollenOS#216]
I am at the desktop and can't find any way to launch the terminal console or other applications available.

**Comment by Meulengracht** [comment]
Use F1 and F2 for now

**Comment by Manish-Kala-Jaat** [comment]
What you think of implementing the mouse cursor and icons to launch application.

**Comment by Meulengracht** [comment]
Its on the todo list on issues this milestone
