### ISSUE TITLE
Userspace

### ISSUE THREAD

**Issue by a11y-spec** [Meulengracht/MollenOS#241]
Plzz would you consider of adding icons on desktop with linux like userspace and i wanna help too!

**Comment by Meulengracht** [comment]
A better userspace navigation will come as a part of this release I'm currently working on, see issue #236

**Comment by a11y-spec** [comment]
oh thanks i want to help too bro :)

**Comment by Meulengracht** [comment]
Would be awesome, you are always free to fork and contribute!
